spring:
  application:
    name: order
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/we_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka